# Generated by Django 5.1.6 on 2025-03-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='catagory',
            field=models.CharField(default='No Applied', max_length=150, verbose_name='Add Catagory'),
            preserve_default=False,
        ),
    ]
